Neos:
  Neos:
    modules:
      management:
        submodules:
          ReactJSDemo:
            label: 'ReactJS Demo'
            controller: Weissheiten\Coaching\NeosPackageWithReactJS\Controller\DashboardController
            description: 'ReactJS Demo'
            icon: graduation-cap
            privilegeTarget: 'Weissheiten.Coaching.NeosPackageWithReactJS:DashboardActions'
            additionalResources:
              styleSheets:
                - 'resource://Weissheiten.Coaching.NeosPackageWithReactJS/Public/Css/reactjsdemo.css'